// Auth types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_IS_LOADING = 'USER_IS_LOADING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const LOGOUT = 'LOGOUT';

// JWT Refresh
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILED = 'REFRESH_TOKEN_FAILED';

// Chat types
export const WORKSPACE_CREATE_SUCCESS = 'WORKSPACE_CREATE_SUCCESS';
export const WORKSPACE_CREATE_FAIL = 'WORKSPACE_CREATE_FAIL';
export const WORKSPACES_FETCHED_SUCCESS = 'WORKSPACES_FETCHED_SUCCESS';
export const WORKSPACES_FETCHED_FAIL = 'WORKSPACES_FETCHED_FAIL';
export const ROOM_CREATE_SUCCESS = 'ROOM_CREATE_SUCCESS';
export const ROOM_CREATE_FAIL = 'ROOM_CREATE_FAIL';
export const ROOMS_LOADING = 'ROOMS_LOADING';
export const ROOMS_LOADED_SUCCESS = 'ROOMS_LOADED_SUCCESS';
export const ROOMS_LOADED_FAIL = 'ROOMS_LOADED_FAIL';
export const CHANGING_ROOM = 'CHANGING_ROOM';
export const FETCH_ROOM_REQUEST = 'FETCH_ROOM_REQUEST';
export const ROOM_FETCH_FAILED = 'ROOM_FETCH_FAILED';
export const ROOM_FETCH_SUCCESS = 'ROOM_FETCH_SUCCESS';
