version: '3'
services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
  django:
    restart: always
    build: ./
    command: python manage.py runserver 0.0.0.0:8100
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - 8100:8100
  frontend:
    restart: always
    build: ./frontend
    volumes:
    - ./frontend:/app
    depends_on:
      - django
